# Generated by Django 5.1.6 on 2025-02-10 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeteranProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('years_of_service', models.IntegerField()),
                ('achievements', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veteranprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(max_length=100)),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veteranprofile')),
            ],
        ),
    ]
