# Generated by Django 5.1.6 on 2025-02-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_updation_remove_news_description_news_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='Questions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
