# Generated by Django 5.1.6 on 2025-02-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_wallofhonor_wallmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='study_materials/')),
                ('purchase_link', models.URLField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
