# Generated by Django 5.1.6 on 2025-03-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/pdfs/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='purchase_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
