# Generated by Django 5.1.6 on 2025-03-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_studymaterial_is_special_studymaterial_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.mocktest'),
        ),
    ]
