# Generated by Django 5.1.6 on 2025-03-11 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userresponse_advice_alter_userresponse_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='advice',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='responses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mocktest'),
        ),
    ]
