# Generated by Django 5.1.6 on 2025-03-12 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_userresponse_advice_userresponse_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
