# Generated by Django 5.1.6 on 2025-03-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='time_limit',
            field=models.IntegerField(default=True, help_text='Time limit in minutes'),
        ),
    ]
