# Generated by Django 5.1.6 on 2025-03-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_message_options_message_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
