# Generated by Django 5.1.6 on 2025-03-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_jobopportunity_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
