# Generated by Django 5.1.6 on 2025-03-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_studymaterial_is_purchased_studymaterial_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktestresult',
            name='test_name',
        ),
        migrations.AddField(
            model_name='mocktestresult',
            name='mock_test',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.mocktest'),
        ),
    ]
