# Generated by Django 5.1.6 on 2025-03-13 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_mocktestresult_test_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='section',
            field=models.CharField(choices=[('artificer apprentice', 'Artificer Apprentice'), ('navy tradesman', 'Navy Tradesman'), ('navy chargeman', 'Navy Chargeman'), ('indian navy entrance test', 'Indian Navy Entrance Test'), ('indian navy angniveer mr', 'Indian Navy Agniveer MR'), ('indian navy angniveer ssr', 'Indian Navy Agniveer SSR'), ('naval dockyard', 'Naval Dockyard')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='mocktestresult',
            name='mock_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mocktest'),
        ),
    ]
