# Generated by Django 5.1.6 on 2025-03-13 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_mocktestresult_improvement_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestresult',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
