# Generated by Django 5.1.6 on 2025-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_payment_payment_id_alter_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=50),
        ),
    ]
