# Generated by Django 5.1.6 on 2025-03-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_campaign_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='improvement_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
