# Generated by Django 5.1.6 on 2025-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mocktest_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updation',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
